// auth actions
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_STORE = "CLEAR_STORE";

//home
export const GET_HOME_FEEDBACK = "GET_HOME_FEEDBACK";
export const GET_HOME_INFO_Details = "GET_HOME_INFO_Details";
export const GET_HOME_LOCATION = "GET_HOME_LOCATION";
export const GET_HOME_PARTNERS = "GET_HOME_PARTNERS";
export const GET_HOME_SLIDER = "GET_HOME_SLIDER";
export const GET_HOME_STEP = "GET_HOME_STEP";
export const GET_HOME_STEP_COTEGORY = "GET_HOME_STEP_COTEGORY";
export const GET_HOME_TOLS = "GET_HOME_TOLS";

//about
export const GET_ABOUT_HEADER = "GET_ABOUT_HEADER";
export const GET_ABOUT_SUSPENSIONS = "GET_ABOUT_SUSPENSIONS";
export const GET_ABOUT_EXPERIENCES = "GET_ABOUT_EXPERIENCES";
export const GET_ABOUT_VEHICLES = "GET_ABOUT_VEHICLES";
export const GET_ABOUT_PROFESSIONS = "GET_ABOUT_PROFESSIONS";
export const GET_ABOUT_SLIDERS = "GET_ABOUT_SLIDERS";
export const GET_ABOUT_VIDEOS = "GET_ABOUT_VIDEOS";

//news

export const GET_NEWS_HEDER = "GET_NEWS_HEDER";
export const GET_NEWS_COTEGORY = "GET_NEWS_COTEGORY";
export const GET_NEWS_MAIN = "GET_NEWS_MAIN";
export const GET_NEWS_SLIDER = "GET_NEWS_SLIDER";
export const LANG_CHANGED = "LANG_CHANGED";

//Service
export const GET_SERVICE_HEADER = "GET_SERVICE_HEADER";
export const GET_SERVICE_AUTO_REPAIRS = "GET_SERVICE_AUTO_REPAIRS";
export const GET_SERVICE_REPAIRS = "GET_SERVICE_REPAIRS";

// CONTACT
export const GET_CONTACT_HEDER = "GET_CONTACT_HEDER";
export const GET_CONTACT_INFO = "GET_CONTACT_INFO";
export const GET_CONTACT_MAIN = "GET_CONTACT_MAIN";

//SiTE MASTER
export const GET_SITE_MASTER = "GET_SITE_MASTER";

//create actions
export const CREATE_HOME_FEEDBACKS = "CREATE_HOME_FEEDBACKS";
export const CREATE_HOME_DETAILS = "CREATE_HOME_DETAILS";
export const CREATE_HOME_LOCATION = "CREATE_HOME_LOCATION";
export const CREATE_HOME_PARTNERS = "CREATE_HOME_PARTNERS";
export const CREATE_HOME_SLIDER = "CREATE_HOME_SLIDER";
export const CREATE_HOME_STEP = "CREATE_HOME_STEP";
export const CREATE_HOME_STEP_COTEGORY = "CREATE_HOME_STEP_COTEGORY";
export const CREATE_HOME_TOOLS = "CREATE_HOME_TOOLS";
export const CREATE_ABOUT_HEADER = "CREATE_ABOUT_HEADER";
export const CREATE_ABOUT_SUSPENSIONS = "CREATE_ABOUT_SUSPENSIONS";
export const CREATE_ABOUT_EXPERIENCES = "CREATE_ABOUT_EXPERIENCES";
export const CREATE_ABOUT_VEHICLES = "CREATE_ABOUT_VEHICLES";
export const CREATE_ABOUT_PROFESSIONS = "CREATE_ABOUT_PROFESSIONS";
export const CREATE_ABOUT_SLIDERS = "CREATE_ABOUT_SLIDERS";
export const CREATE_ABOUT_VIDEO = "CREATE_ABOUT_VIDEO";
export const CREATE_SERVICE_HOME = "CREATE_SERVICE_HOME";
export const CREATE_SERVICE_AUTO_REPAIRS = "CREATE_SERVICE_AUTO_REPAIRS";
export const CREATE_SERVICE_REPAIRS = "CREATE_SERVICE_REPAIRS";
export const CREATE_NEWS_HEADER = "CREATE_NEWS_HEADER";
export const CREATE_NEWS_CATEGORY = "CREATE_NEWS_CATEGORY";
export const CREATE_NEWS_MAIN = "CREATE_NEWS_MAIN";
export const CREATE_NEWS_SLIDERS = "CREATE_NEWS_SLIDERS";
export const CREATE_CONTACT_HEADER = "CREATE_CONTACT_HEADER";
export const CREATE_CONTACT_INFO = "CREATE_CONTACT_INFO";
export const CREATE_SITE_MASTER = "CREATE_SITE_MASTER";

// update actions
export const UPDATE_HOME_FEEDBACKS = "UPDATE_HOME_FEEDBACKS";
export const UPDATE_HOME_DETAILS = "UPDATE_HOME_DETAILS";

// delete actions

export const DELETE_HOME_FEEDBACKS = "DELETE_HOME_FEEDBACKS";
export const DELETE_HOME_DETAILS = "DELETE_HOME_DETAILS";
export const DELETE_HOME_LOCATION = "DELETE_HOME_LOCATION";
export const DELETE_HOME_PARTNERS = "DELETE_HOME_PARTNERS";
export const DELETE_HOME_SLIDER = "DELETE_HOME_SLIDER";
export const DELETE_HOME_STEP = "DELETE_HOME_STEP";
export const DELETE_HOME_STEP_COTEGORY = "DELETE_HOME_STEP_COTEGORY";
export const DELETE_HOME_TOOLS = "DELETE_HOME_TOOLS";

export const DELETE_ABOUT_HEADER = "DELETE_ABOUT_HEADER";
export const DELETE_ABOUT_SUSPENSIONS = "DELETE_ABOUT_SUSPENSIONS";
export const DELETE_ABOUT_EXPERIENCES = "DELETE_ABOUT_EXPERIENCES";
export const DELETE_ABOUT_VEHICLES = "DELETE_ABOUT_VEHICLES";
export const DELETE_ABOUT_PROFESSIONS = "DELETE_ABOUT_PROFESSIONS";
export const DELETE_ABOUT_SLIDERS = "DELETE_ABOUT_SLIDERS";
export const DELETE_ABOUT_VIDEOS = "DELETE_ABOUT_VIDEOS";
export const  DELETE_ABOUT_TOOLS = "DELETE_ABOUT_TOOLS";


export const DELETE_SERVICE_HEADER = "DELETE_SERVICE_HEADER";
export const DELETE_SERVICE_AUTO_REPAIRS = "DELETE_SERVICE_AUTO_REPAIRS";
export const DELETE_SERVICE_REPAIRS = "DELETE_SERVICE_REPAIRS";

export const DELETE_NEWS_HEADER = "DELETE_NEWS_HEADER";
export const DELETE_NEWS_CATEGORY = "DELETE_NEWS_CATEGORY";
export const DELETE_NEWS_MAIN = "DELETE_NEWS_MAIN";
export const DELETE_NEWS_SLIDER = "DELETE_NEWS_SLIDER";

export const DELETE_CONTACT_HEADER = "DELETE_CONTACT_HEADER";
export const DELETE_CONTACT_INFO = "DELETE_CONTACT_INFO";
export const DELETE_CONTACT_MAIN = "DELETE_CONTACT_MAIN";

export const DELETE_SITE_MASTER = "DELETE_SITE_MASTER";
// export const DELETE_HOME_DETAILS = "DELETE_HOME_DETAILS";
// export const DELETE_HOME_LOCATION = "DELETE_HOME_LOCATION";
// export const DELETE_HOME_PARTNERS = "DELETE_HOME_PARTNERS";
// export const DELETE_HOME_SLIDER = "DELETE_HOME_SLIDER";
// export const DELETE_HOME_STEP = "DELETE_HOME_STEP";
// export const DELETE_HOME_STEP_COTEGORY = "DELETE_HOME_STEP_COTEGORY";
// export const DELETE_HOME_TOOLS = "DELETE_HOME_TOOLS";
